Repository kira2505/OnlineStore, pull requests merged in 2025-07, with the labels that each got.

#42 add and update
  src/main/java/com/telran/store/controller/OrderController.java
  src/main/java/com/telran/store/service/OrderScheduleService.java
  src/main/java/com/telran/store/service/OrderServiceImpl.java
Labels: enhancement

#46 fix
  src/test/java/com/telran/store/service/PaymentServiceImplTest.java
Labels: enhancement, good first issue

#53 fix and update
  src/main/java/com/telran/store/configuration/DbInitializer.java
  src/main/java/com/telran/store/controller/ShopUserController.java
  src/main/java/com/telran/store/service/ShopUserServiceImpl.java
  src/main/resources/db/changelog/db.changelog-master.xml
  src/main/resources/db/changelog/filldata/data.sql
Labels: enhancement

#54 fix tests
  src/main/java/com/telran/store/service/ProductServiceImpl.java
  src/test/java/com/telran/store/service/ProductServiceImplTest.java
Labels: enhancement

#55 add and update
  src/main/java/com/telran/store/configuration/SecurityConfig.java
  src/main/java/com/telran/store/controller/ReportController.java
  src/main/java/com/telran/store/dto/ProductSalesDTO.java
  src/main/java/com/telran/store/repository/OrderRepository.java
  src/main/java/com/telran/store/service/ReportService.java
  src/main/java/com/telran/store/service/ReportServiceImp.java
Labels: enhancement

#56 Y sprint four taskone
  pom.xml
  src/main/java/com/telran/store/configuration/SecurityConfig.java
  src/main/java/com/telran/store/controller/CartController.java
  src/main/java/com/telran/store/controller/CategoryController.java
  src/main/java/com/telran/store/controller/FavoriteController.java
  src/main/java/com/telran/store/controller/OrderController.java
  src/main/java/com/telran/store/controller/PaymentController.java
  src/main/java/com/telran/store/controller/ProductController.java
  src/main/java/com/telran/store/controller/ShopUserController.java
  src/main/java/com/telran/store/dto/AddToCartRequestDto.java
  src/main/java/com/telran/store/dto/CategoryCreateDto.java
  src/main/java/com/telran/store/dto/FavoriteCreateDto.java
  src/main/java/com/telran/store/dto/OrderCreateDto.java
  src/main/java/com/telran/store/dto/OrderItemCreateDto.java
  src/main/java/com/telran/store/dto/PaymentCreateDto.java
  src/main/java/com/telran/store/dto/ProductCreateDto.java
  src/main/java/com/telran/store/dto/ShopUserCreateDto.java
  src/main/java/com/telran/store/dto/ShopUserDto.java
  src/main/java/com/telran/store/exception/NotFoundProductWithDiscountPrice.java
  src/main/java/com/telran/store/handler/CommonExceptionHandler.java
  src/main/java/com/telran/store/service/ProductService.java
  src/main/java/com/telran/store/service/ProductServiceImpl.java
Labels: enhancement, good first issue

#57 add update
  src/main/java/com/telran/store/controller/ReportController.java
  src/main/java/com/telran/store/handler/CommonExceptionHandler.java
  src/main/java/com/telran/store/repository/OrderRepository.java
  src/main/java/com/telran/store/service/ReportService.java
  src/main/java/com/telran/store/service/ReportServiceImp.java
  src/main/java/com/telran/store/service/ShopUserServiceImpl.java
Labels: enhancement

#58 update
  src/main/java/com/telran/store/controller/ReportController.java
  src/main/java/com/telran/store/dto/ReportRequestDto.java
  src/main/java/com/telran/store/service/ReportService.java
  src/main/java/com/telran/store/service/ReportServiceImp.java
Labels: enhancement

#59 add
  src/main/java/com/telran/store/controller/CartController.java
  src/main/java/com/telran/store/controller/CategoryController.java
  src/main/java/com/telran/store/controller/PaymentController.java
  src/main/java/com/telran/store/controller/ProductController.java
  src/main/java/com/telran/store/dto/OrderPendingPaidDto.java
  src/main/java/com/telran/store/dto/ProductResponseDto.java
  src/main/java/com/telran/store/repository/OrderRepository.java
  src/main/java/com/telran/store/service/PaymentService.java
  src/main/java/com/telran/store/service/PaymentServiceImpl.java
  src/main/java/com/telran/store/service/ProductServiceImpl.java
  src/test/java/com/telran/store/controller/PaymentControllerTest.java
  src/test/java/com/telran/store/controller/ProductControllerTest.java
  src/test/java/com/telran/store/service/PaymentServiceImplTest.java
  src/test/java/com/telran/store/service/ProductServiceImplTest.java
Labels: enhancement, good first issue

#62 update and add
  src/main/java/com/telran/store/configuration/SwaggerConfiguration.java
  src/main/java/com/telran/store/controller/CategoryController.java
  src/main/java/com/telran/store/controller/OrderController.java
  src/main/java/com/telran/store/controller/ReportController.java
  src/main/java/com/telran/store/controller/ShopUserApi.java
  src/main/java/com/telran/store/controller/ShopUserController.java
  src/main/java/com/telran/store/dto/OrderCreateDto.java
  src/main/java/com/telran/store/dto/OrderItemCreateDto.java
  src/main/java/com/telran/store/dto/OrderItemResponseDto.java
  src/main/java/com/telran/store/dto/OrderPendingPaidDto.java
  src/main/java/com/telran/store/dto/ShopUserCreateDto.java
  src/main/java/com/telran/store/dto/ShopUserDto.java
  src/main/java/com/telran/store/dto/ShopUserResponseDto.java
  src/main/java/com/telran/store/mapper/OrderMapper.java
  src/main/java/com/telran/store/mapper/ShopUserMapper.java
  src/main/java/com/telran/store/repository/OrderItemRepository.java
  src/main/java/com/telran/store/repository/OrderRepository.java
  src/main/java/com/telran/store/service/OrderScheduleService.java
  src/main/java/com/telran/store/service/OrderService.java
  src/main/java/com/telran/store/service/OrderServiceImpl.java
  src/main/java/com/telran/store/service/ReportServiceImp.java
  src/main/java/com/telran/store/service/ShopUserDetailService.java
  src/main/java/com/telran/store/service/ShopUserService.java
  src/main/java/com/telran/store/service/ShopUserServiceImpl.java
  src/main/java/com/telran/store/service/security/JwtFilter.java
  src/main/resources/application.properties
Labels: enhancement, good first issue

#64 update and add
  src/main/java/com/telran/store/configuration/SecurityConfig.java
  src/main/java/com/telran/store/configuration/SwaggerConfiguration.java
  src/main/java/com/telran/store/controller/AuthController.java
  src/main/java/com/telran/store/controller/CategoryApi.java
  src/main/java/com/telran/store/controller/CategoryController.java
  src/main/java/com/telran/store/controller/ReportApi.java
  src/main/java/com/telran/store/controller/ReportController.java
  src/main/java/com/telran/store/controller/ShopUserApi.java
  src/main/java/com/telran/store/controller/ShopUserController.java
  src/main/java/com/telran/store/service/ShopUserServiceImpl.java
Labels: enhancement, good first issue

#63 add and fix
  src/main/java/com/telran/store/controller/CartApi.java
  src/main/java/com/telran/store/controller/CartController.java
  src/main/java/com/telran/store/controller/FavoriteApi.java
  src/main/java/com/telran/store/controller/FavoriteController.java
  src/main/java/com/telran/store/controller/PaymentApi.java
  src/main/java/com/telran/store/controller/PaymentController.java
  src/main/java/com/telran/store/controller/ProductApi.java
  src/main/java/com/telran/store/controller/ProductController.java
  src/main/java/com/telran/store/entity/Favorite.java
  src/main/java/com/telran/store/repository/FavoriteRepository.java
  src/main/java/com/telran/store/service/FavoriteService.java
  src/main/java/com/telran/store/service/FavoriteServiceImpl.java
  src/test/java/com/telran/store/controller/FavoriteControllerTest.java
  src/test/java/com/telran/store/service/CartServiceImplTest.java
  src/test/java/com/telran/store/service/FavoriteServiceImplTest.java
Labels: enhancement, good first issue

#67 fix
  src/main/java/com/telran/store/controller/CartApi.java
  src/main/java/com/telran/store/controller/CartController.java
  src/main/java/com/telran/store/controller/FavoriteApi.java
  src/main/java/com/telran/store/controller/FavoriteController.java
  src/main/java/com/telran/store/controller/PaymentApi.java
  src/main/java/com/telran/store/controller/PaymentController.java
  src/main/java/com/telran/store/controller/ProductApi.java
  src/main/java/com/telran/store/controller/ProductController.java
Labels: fix

#68 update
  src/main/java/com/telran/store/configuration/DbInitializer.java
  src/main/java/com/telran/store/configuration/SecurityConfig.java
  src/main/java/com/telran/store/controller/CategoryApi.java
  src/main/java/com/telran/store/controller/CategoryController.java
  src/main/java/com/telran/store/controller/OrderApi.java
  src/main/java/com/telran/store/controller/OrderController.java
  src/main/java/com/telran/store/controller/ReportApi.java
  src/main/java/com/telran/store/controller/ReportController.java
  src/main/java/com/telran/store/controller/ShopUserApi.java
  src/main/java/com/telran/store/controller/ShopUserController.java
  src/main/java/com/telran/store/dto/CartResponseDto.java
  src/main/java/com/telran/store/dto/OrderItemResponseDto.java
  src/main/java/com/telran/store/dto/ProductSalesDTO.java
  src/main/java/com/telran/store/mapper/OrderItemMapper.java
  src/main/java/com/telran/store/repository/OrderItemRepository.java
  src/main/java/com/telran/store/repository/OrderRepository.java
  src/main/java/com/telran/store/service/CategoryServiceImpl.java
  src/main/java/com/telran/store/service/OrderServiceImpl.java
  src/main/java/com/telran/store/service/ReportServiceImp.java
  src/main/java/com/telran/store/service/security/JwtFilter.java
Labels: fix

#69 fix and add
  src/main/java/com/telran/store/controller/CartApi.java
  src/main/java/com/telran/store/controller/FavoriteApi.java
  src/main/java/com/telran/store/controller/PaymentApi.java
  src/main/java/com/telran/store/controller/ProductApi.java
  src/main/java/com/telran/store/entity/Product.java
  src/main/java/com/telran/store/service/CartServiceImpl.java
  src/main/java/com/telran/store/service/ProductServiceImpl.java
Labels: enhancement, fix

#70 update and add
  src/main/java/com/telran/store/controller/CategoryApi.java
  src/main/java/com/telran/store/controller/CategoryController.java
  src/main/java/com/telran/store/controller/OrderApi.java
  src/main/java/com/telran/store/controller/OrderController.java
  src/main/java/com/telran/store/controller/ReportController.java
  src/main/java/com/telran/store/controller/ShopUserApi.java
  src/main/java/com/telran/store/controller/ShopUserController.java
  src/main/java/com/telran/store/service/CategoryServiceImpl.java
  src/main/java/com/telran/store/service/OrderScheduleService.java
  src/main/java/com/telran/store/service/OrderServiceImpl.java
  src/main/java/com/telran/store/service/ShopUserServiceImpl.java
  src/main/resources/application.properties
Labels: enhancement, fix

#71 add, fix
  src/main/java/com/telran/store/controller/CartApi.java
  src/main/java/com/telran/store/controller/FavoriteApi.java
  src/main/java/com/telran/store/controller/ProductApi.java
  src/main/java/com/telran/store/dto/ProductCreateDto.java
  src/main/java/com/telran/store/entity/Cart.java
  src/main/java/com/telran/store/entity/CartItem.java
  src/main/java/com/telran/store/entity/Category.java
  src/main/java/com/telran/store/entity/Favorite.java
  src/main/java/com/telran/store/entity/Order.java
  src/main/java/com/telran/store/entity/Product.java
  src/main/java/com/telran/store/entity/ShopUser.java
  src/main/java/com/telran/store/exception/FavoriteAlreadyExistsException.java
  src/main/java/com/telran/store/handler/CommonExceptionHandler.java
  src/main/java/com/telran/store/repository/FavoriteRepository.java
  src/main/java/com/telran/store/service/CartServiceImpl.java
  src/main/java/com/telran/store/service/FavoriteServiceImpl.java
  src/main/java/com/telran/store/service/PaymentServiceImpl.java
  src/main/java/com/telran/store/service/ProductServiceImpl.java
  src/main/resources/application.properties
  src/test/java/com/telran/store/controller/ReportControllerTest.java
  src/test/java/com/telran/store/service/CartServiceImplTest.java
  src/test/java/com/telran/store/service/FavoriteServiceImplTest.java
  src/test/java/com/telran/store/service/ReportServiceImpTest.java
Labels: enhancement, fix

#73 update
  src/main/java/com/telran/store/service/OrderServiceImpl.java
Labels: fix

#78 fix
  pom.xml
  src/main/java/com/telran/store/service/CartServiceImpl.java
  src/test/java/com/telran/store/service/CartServiceImplTest.java
Labels: fix
