Repository kira2505/OnlineStore, pull requests merged in 2025-06, with the labels that each got.

#2 add Product entity
  src/main/java/com/telran/store/entity/Product.java
Labels: enhancement, good first issue

#1 add user entity
  src/main/java/com/telran/store/entity/ShopUser.java
Labels: good first issue

#4 Create entity(Product, Favorite), empty dto
  src/main/java/com/telran/store/StoreApp.java
  src/main/java/com/telran/store/dto/ProductResponseDto.java
  src/main/java/com/telran/store/dto/favoriteCreateDto.java
  src/main/java/com/telran/store/dto/favoriteResponseDto.java
  src/main/java/com/telran/store/dto/productCreateDto.java
  src/main/java/com/telran/store/entity/Favorites.java
  src/main/java/com/telran/store/entity/Product.java
Labels: enhancement, good first issue

#8 add changes to DTO and Mapper and Controller
  src/main/java/com/telran/store/controller/FavoriteController.java
  src/main/java/com/telran/store/controller/ProductController.java
  src/main/java/com/telran/store/dto/FavoriteCreateDto.java
  src/main/java/com/telran/store/dto/FavoriteResponseDto.java
  src/main/java/com/telran/store/dto/ProductCreateDto.java
  src/main/java/com/telran/store/dto/ProductResponseDto.java
  src/main/java/com/telran/store/entity/Favorite.java
  src/main/java/com/telran/store/entity/Product.java
  src/main/java/com/telran/store/mapper/FavoriteMapper.java
  src/main/java/com/telran/store/mapper/ProductMapper.java
  src/main/java/com/telran/store/mapper/UserMapper.java
Labels: enhancement, good first issue

#9 update Shop User controller, dto, entity
  src/main/java/com/telran/store/controller/ShopUserController.java
  src/main/java/com/telran/store/dto/ShopUserResponseDto.java
  src/main/java/com/telran/store/entity/ShopUser.java
Labels: enhancement

#12 update mapper and dto
  src/main/java/com/telran/store/dto/ShopUserResponseDto.java
  src/main/java/com/telran/store/mapper/ShopUserMapper.java
Labels: enhancement

#13 update controller and service, create tests
  pom.xml
  src/main/java/com/telran/store/dto/CategoryCreateDto.java
  src/main/java/com/telran/store/dto/CategoryResponseDto.java
  src/main/java/com/telran/store/dto/ShopUserCreateDto.java
  src/main/java/com/telran/store/dto/ShopUserResponseDto.java
  src/main/java/com/telran/store/entity/Category.java
  src/test/java/com/telran/store/controller/CategoryControllerTest.java
  src/test/java/com/telran/store/controller/ShopUserControllerTest.java
  src/test/java/com/telran/store/service/CategoryServiceImplTest.java
  src/test/java/com/telran/store/service/ShopUserServiceImplTest.java
  src/test/resources/data.sql
  src/test/resources/schema.sql
Labels: enhancement, good first issue

#14 tests
  src/main/java/com/telran/store/dto/FavoriteResponseDto.java
  src/main/java/com/telran/store/dto/ProductCreateDto.java
  src/main/java/com/telran/store/dto/ProductResponseDto.java
  src/main/java/com/telran/store/entity/Favorite.java
  src/main/java/com/telran/store/entity/Product.java
  src/main/java/com/telran/store/repository/ProductRepository.java
  src/test/java/com/telran/store/controller/FavoriteControllerTest.java
  src/test/java/com/telran/store/controller/ProductControllerTest.java
  src/test/java/com/telran/store/controller/ShopUserControllerTest.java
  src/test/java/com/telran/store/service/FavoriteServiceImplTest.java
  src/test/java/com/telran/store/service/ProductServiceImlTest.java
  src/test/resources/data.sql
  src/test/resources/schema.sql
Labels: enhancement, good first issue

#16 update controller, dto, service, entity and mapper
  project.md
  src/main/java/com/telran/store/controller/FavoriteController.java
  src/main/java/com/telran/store/dto/CategoryDto.java
  src/main/java/com/telran/store/dto/ProductCreateDto.java
  src/main/java/com/telran/store/entity/Category.java
  src/main/java/com/telran/store/entity/Favorite.java
  src/main/java/com/telran/store/entity/Product.java
  src/main/java/com/telran/store/entity/ShopUser.java
  src/main/java/com/telran/store/mapper/CategoryMapper.java
  src/main/java/com/telran/store/mapper/ProductMapper.java
  src/main/java/com/telran/store/service/FavoriteService.java
  src/main/java/com/telran/store/service/FavoriteServiceImpl.java
  src/main/resources/application.properties
Labels: good first issue

#18 sprint two task three add Data Filtering
  src/main/java/com/telran/store/controller/ProductController.java
  src/main/java/com/telran/store/repository/ProductRepository.java
  src/main/java/com/telran/store/service/ProductService.java
  src/main/java/com/telran/store/service/ProductServiceIml.java
Labels: enhancement, good first issue

#20 add Handler
  src/main/java/com/telran/store/handler/CommonExceptionHandler.java
Labels: enhancement, good first issue

#21 Connect Liquibase
  pom.xml
  src/main/java/com/telran/store/entity/Product.java
  src/main/resources/application.properties
  src/main/resources/db/changelog/db.changelog-master.xml
Labels: enhancement, good first issue

#22 Sprint two
  pom.xml
  project.md
  src/main/java/com/telran/store/controller/CategoryController.java
  src/main/java/com/telran/store/controller/ProductController.java
  src/main/java/com/telran/store/controller/ShopUserController.java
  src/main/java/com/telran/store/entity/Product.java
  src/main/java/com/telran/store/handler/CommonExceptionHandler.java
  src/main/java/com/telran/store/mapper/CategoryMapper.java
  src/main/java/com/telran/store/mapper/ProductMapper.java
  src/main/java/com/telran/store/mapper/ShopUserMapper.java
  src/main/java/com/telran/store/repository/ProductRepository.java
  src/main/java/com/telran/store/service/CategoryService.java
  src/main/java/com/telran/store/service/CategoryServiceImpl.java
  src/main/java/com/telran/store/service/ProductService.java
  src/main/java/com/telran/store/service/ProductServiceImpl.java
  src/main/java/com/telran/store/service/ShopUserService.java
  src/main/java/com/telran/store/service/ShopUserServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/db/changelog/db.changelog-master.xml
  src/test/java/com/telran/store/controller/ProductControllerTest.java
  src/test/java/com/telran/store/service/ProductServiceImplTest.java
Labels: enhancement, good first issue

#32 update and create
  pom.xml
  src/main/java/com/telran/store/controller/CartController.java
  src/main/java/com/telran/store/dto/AddToCartRequestDto.java
  src/main/java/com/telran/store/repository/CartItemRepository.java
  src/main/java/com/telran/store/service/CartService.java
  src/main/java/com/telran/store/service/CartServiceImpl.java
  src/main/java/com/telran/store/service/OrderServiceImpl.java
  src/test/java/com/telran/store/controller/CartControllerTest.java
  src/test/java/com/telran/store/service/CartServiceImplTest.java
Labels: enhancement, good first issue

#35 update
  src/main/java/com/telran/store/entity/Order.java
  src/main/java/com/telran/store/mapper/OrderMapper.java
  src/main/java/com/telran/store/service/PaymentServiceImpl.java
Labels: enhancement, good first issue

#37 add
  src/main/java/com/telran/store/controller/PaymentController.java
  src/main/java/com/telran/store/dto/PaymentResponseDto.java
  src/main/java/com/telran/store/mapper/PaymentMapper.java
  src/main/java/com/telran/store/service/OrderScheduleService.java
  src/main/java/com/telran/store/service/PaymentService.java
  src/main/java/com/telran/store/service/PaymentServiceImpl.java
Labels: enhancement, good first issue

#38 add and update
  project.md
  src/main/java/com/telran/store/controller/PaymentController.java
  src/main/java/com/telran/store/dto/OrderResponseDto.java
  src/main/java/com/telran/store/dto/PaymentResponseDto.java
  src/main/java/com/telran/store/entity/Order.java
  src/main/java/com/telran/store/entity/Payment.java
  src/main/java/com/telran/store/enums/PaymentStatus.java
  src/main/java/com/telran/store/enums/Status.java
  src/main/java/com/telran/store/repository/OrderRepository.java
  src/main/java/com/telran/store/service/OrderScheduleService.java
  src/main/java/com/telran/store/service/OrderService.java
  src/main/java/com/telran/store/service/OrderServiceImpl.java
  src/main/java/com/telran/store/service/PaymentScheduleService.java
  src/main/java/com/telran/store/service/PaymentServiceImpl.java
  src/main/resources/db/changelog/db.changelog-master.xml
Labels: enhancement

#41 update
  src/main/java/com/telran/store/dto/OrderResponseDto.java
  src/main/java/com/telran/store/dto/PaymentResponseDto.java
  src/main/java/com/telran/store/entity/Order.java
  src/main/java/com/telran/store/entity/Payment.java
  src/main/java/com/telran/store/mapper/OrderMapper.java
  src/main/java/com/telran/store/mapper/PaymentMapper.java
  src/main/java/com/telran/store/service/OrderScheduleService.java
  src/main/java/com/telran/store/service/OrderService.java
  src/main/java/com/telran/store/service/OrderServiceImpl.java
  src/main/java/com/telran/store/service/PaymentServiceImpl.java
  src/main/resources/db/changelog/db.changelog-master.xml
Labels: enhancement
